const MessageActionTypes = {
  ADD_MESSAGE_LIST: "ADD_MESSAGE_LIST",
  FETCH_MESSAGES_SUCCESS: "FETCH_MESSAGES_SUCCESS",
  FETCH_MESSAGES_FAILURE: "FETCH_MESSAGES_FAILURE",
};

export default MessageActionTypes;
