const RoomActionTypes = {
  SET_CURRENT_ROOM: "SET_CURRENT_ROOM",
  GET_ALL_ROOMS: "GET_ALL_ROOMS",
  SET_ROOM_LIST: "SET_ROOM_LIST",
  SET_TOGGLE_DROPDOWN: "SET_TOGGLE_DROPDOWN",
  SET_TOGGLE_OPTIONS_POPUP: "SET_TOGGLE_OPTIONS_POPUP",
  DELETE_ROOM: "DELETE_ROOM",
  ADD_ROOM_LIST: "ADD_ROOM_LIST",
};

export default RoomActionTypes;
