const RoomActionTypes = {
  SET_CURRENT_ROOM: "SET_CURRENT_ROOM",
  GET_ALL_ROOMS: "GET_ALL_ROOMS",
  SET_ROOM_LIST: "SET_ROOM_LIST",
  SET_TOGGLE_DROPDOWN: "SET_TOGGLE_DROPDOWN",
  SET_TOGGLE_DELETE: "SET_TOGGLE_DELETE",
  DELETE_ROOM: "DELETE_ROOM",
};

export default RoomActionTypes;
