const RoomActionTypes = {
  SET_CURRENT_ROOM: "SET_CURRENT_ROOM",
  SET_TOGGLE_DROPDOWN: "SET_TOGGLE_DROPDOWN",
  SET_TOGGLE_OPTIONS_POPUP: "SET_TOGGLE_OPTIONS_POPUP",
  DELETE_ROOM: "DELETE_ROOM",
  ADD_ROOM_LIST: "ADD_ROOM_LIST",
  TOGGLE_USER_IN_ROOM: "TOGGLE_USER_IN_ROOM",
  FETCH_ROOMS_SUCCESS: "FETCH_ROOMS_SUCCESS",
  FETCH_ROOMS_FAILURE: "FETCH_ROOMS_FAILURE",
};

export default RoomActionTypes;
