const UserActionTypes = {
  LOGIN_USER: "LOGIN_USER",
  SIGNUP_USER: "SIGNUP_USER",
  LOGOUT_USER: "LOGOUT_USER",
  IS_AUTHENTICATED: "IS_AUTHENTICATED",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  TOGGLE_UPDATE_PROFILE: "TOGGLE_UPDATE_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
};

export default UserActionTypes;
